version: "3.3"

services:
  alma-inventory:
    image: terrywbrady/alma-inventory-jetty
    ports:
      - 80:8080
    volumes:
      - "./local.prop:/var/data/local.prop"
      - "./gsheet.prop.json:/var/lib/jetty/webapps/ROOT/gsheet.prop.json"
    tty: true
    stdin_open: true
